pubnishment-Ticks: 12000
coldnessCause: "&c✘ &3你冻死了,将接受惩罚."
hotnessCause: "&c✘ &3你热死了,将接受惩罚."
darknessCause: "&c✘ &3你因为过于黑暗死了,将接受惩罚."
beeMineCause: "&c✘ &3你被有毒的地板毒死了,将接受惩罚."
toothTrapCause: "&c✘ &3你被有刺的地板扎死了,将接受惩罚."
blowArrowCause: "&c✘ &3你死于吹箭,将接受惩罚."
invaildSleepnessCause: "&c✘ &3你在不该休息的地方休息,将接受惩罚."
dropMoneyMessage: "&c✘ &3由于你的死亡,你在({location}&3)附近掉落了&c{money}&3金币."
getMoneyFromBatMessage: "&a✔ &3你成功从金币蝙蝠上获得了&c{money}&3金币."
voidCause: "&c✘ &3你掉出了这个世界,将接受惩罚."
fallCause: "&c✘ &3你摔死了,将接受惩罚."
fallingBlockCause: "&c✘ &3你被掉落的方块压扁了,将接受惩罚."
suicideCause: "&c✘ &3你自杀了,将接受惩罚."